#!/usr/bin/env python3
"""Generate fltk98.bat - a COMMAND.COM-compatible FLTK build for Windows 98.

build_fltk.bat drives FLTK with `for /f` over fltk_core.list / fltk_gl.list and
picks gcc-vs-g++ with `if /I "%%~xf"==".c"`. COMMAND.COM has neither `for /f`
nor the `%%~x` modifiers, so the loop cannot be ported - it has to be unrolled.
This script does the unrolling on the dev host, keeping FLTK's own .list files
as the single source of truth. Re-run it whenever a .list file changes.

Two Win98 constraints shape the emitted batch:

  * DOS passes a program's command tail in a 127-byte PSP field. A direct
    translation of build_fltk.bat's compile line is 238 characters for the
    longest source name, so it would be silently truncated. Three things bring
    it to ~122: cd into the source directory so sources are bare filenames,
    move the include paths into CPLUS_INCLUDE_PATH, and move the -D flags into
    a generated w98.h pulled in with -include.

  * COMMAND.COM's own builtins resolve 8.3 names only. The emitted batch keeps
    every `if exist` argument 8.3-clean - hence the fltkok.tag sentinel rather
    than testing for libfltk_gl.a, whose 10-character stem is not 8.3.

Usage:  python3 tools/genfltk98.py        (run from the repo root)
"""

import os
import sys

REPO = os.path.dirname(os.path.abspath(os.path.join(__file__, "..")))
LISTDIR = os.path.join(REPO, "vendor", "fltk-1.3")
FLROOT = os.path.join(LISTDIR, "FL")
BAT = os.path.join(REPO, "fltk98.bat")
HDR = os.path.join(FLROOT, "w98.h")

LIMIT = 127          # DOS PSP command tail
DC = r"C:\Dev-Cpp\bin"

# w98.h carries what build_fltk.bat passed as -D flags. WINVER/_WIN32_WINNT at
# 0x0500 only make Win2000+ symbols DECLARED (XBUTTON1/GET_XBUTTON_WPARAM,
# BITMAPV5HEADER); FLTK's win32 backend has no version-gated code blocks, so no
# new runtime paths are enabled and both sites are dead code for the editor.
# FL_LIBRARY is set while building the library itself.
HEADER = """/* Generated by tools/genfltk98.py - do not edit by hand.
 *
 * Carries the -D flags build_fltk.bat puts on the command line. They live in a
 * header instead because the Win98 build has to fit DOS's 127-byte command
 * tail, and the define block alone is 66 characters.
 *
 * -include pulls this in ahead of every FLTK source, so the macros are set
 * before any FLTK or windows header is reached.
 */
#ifndef SOOB_W98_H
#define SOOB_W98_H

#ifndef WIN32
#define WIN32 1
#endif

/* 0x0500 makes Win2000+ symbols declared, not used - see genfltk98.py. */
#undef WINVER
#define WINVER 0x0500
#undef _WIN32_WINNT
#define _WIN32_WINNT 0x0500

#ifndef FL_LIBRARY
#define FL_LIBRARY 1
#endif

#endif
"""


def read_list(name):
    path = os.path.join(LISTDIR, name)
    out = []
    for line in open(path):
        line = line.strip()
        if line and not line.startswith("#"):
            out.append(line)
    return out


def emit(lines, core, gl):
    a = lines.append
    a("@echo off")
    a("echo === FLTK 1.3.11 static libs for the SOOB editor - Win98 ===")
    a("echo.")
    a("")
    a("REM  GENERATED by tools/genfltk98.py from fltk_core.list / fltk_gl.list.")
    a("REM  Do not edit by hand - re-run the generator instead.")
    a("REM")
    a("REM  COMMAND.COM has no `for /f` and no `%%~x` modifiers, so the loop in")
    a("REM  build_fltk.bat is unrolled here: one explicit line per source.")
    a("REM")
    a("REM  Run it with the current directory on the repo root:")
    a("REM      X:")
    a("REM      cd \\Projects\\SOOB-Engine")
    a("REM      fltk98")
    a("REM")
    a("REM  Delete vendor\\fltk-1.3\\FL\\lib to force a full rebuild.")
    a("")
    a("REM ---- Current-directory check. main.cpp is a valid 8.3 name, so this")
    a("REM ---- test raises no long-filename question.")
    a("if not exist main.cpp goto nocwd")
    a("")
    a("set DC=%s" % DC)
    a("")
    a("REM ---- Everything below runs from FLTK's source directory. That keeps")
    a("REM ---- sources as bare filenames and objects two levels away, which is")
    a("REM ---- what holds the compile lines inside DOS's 127-byte command tail.")
    a("cd vendor\\fltk-1.3\\FL\\src")
    a("")
    a("REM ---- Include paths via the environment rather than -I, same reason.")
    a("REM ---- Relative to the directory we just changed into: .. is FL, . is src.")
    a("set CPLUS_INCLUDE_PATH=..;.")
    a("set C_INCLUDE_PATH=..;.")
    a("")
    a("REM ---- Objects live under FL\\lib, which .gitignore already covers.")
    a("if not exist ..\\lib\\nul mkdir ..\\lib")
    a("if not exist ..\\lib\\o\\nul mkdir ..\\lib\\o")
    a("if not exist ..\\lib\\og\\nul mkdir ..\\lib\\og")
    a("")
    a("REM ---- Build sentinel. libfltk_gl.a has a 10-character stem, which is")
    a("REM ---- not 8.3, and COMMAND.COM's if-exist resolves 8.3 names only - so")
    a("REM ---- the completed build is flagged with this 8.3-clean tag instead.")
    a("if exist ..\\lib\\fltkok.tag goto done")
    a("")

    for label, srcs, objdir in (("core", core, r"..\lib\o"),
                                ("GL", gl, r"..\lib\og")):
        a("echo Compiling FLTK %s - this takes a while..." % label)
        for s in srcs:
            stem = s.rsplit(".", 1)[0]
            # .c files must be compiled as C, not C++: FLTK's UTF-16 code passes
            # unsigned short* to the ...W() APIs, valid in C (where wchar_t IS
            # unsigned short) but an invalid conversion in C++. Matches FLTK's
            # own build, which uses $(CC) for CFILES.
            cc = "gcc" if s.endswith(".c") else "g++"
            a("%%DC%%\\%s.exe -O2 -w -include ..\\w98.h -c %s -o %s\\%s.o"
              % (cc, s, objdir, stem))
            a("if errorlevel 1 goto failed")
        a("")

    a("echo Archiving libfltk.a ...")
    a("%DC%\\ar.exe rcs ..\\lib\\libfltk.a ..\\lib\\o\\*.o")
    a("if errorlevel 1 goto failed")
    a("")
    a("echo Archiving libfltk_gl.a ...")
    a("%DC%\\ar.exe rcs ..\\lib\\libfltk_gl.a ..\\lib\\og\\*.o")
    a("if errorlevel 1 goto failed")
    a("")
    a("echo done> ..\\lib\\fltkok.tag")
    a("")
    a(":done")
    a("cd ..\\..\\..\\..")
    a("echo.")
    a("echo === FLTK ready: vendor\\fltk-1.3\\FL\\lib ===")
    a("echo Now run the editor build - its FLTK var already points there.")
    a("goto end")
    a("")
    a(":failed")
    a("cd ..\\..\\..\\..")
    a("echo.")
    a("echo === FLTK BUILD FAILED ===")
    a("echo If a single file breaks on GCC 3.4, note which one -- late 1.3.x")
    a("echo patches occasionally need a small tweak on the old compiler.")
    a("pause")
    a("goto end")
    a("")
    a(":nocwd")
    a("echo ERROR: wrong current directory - main.cpp is not here.")
    a("echo Run this from the repo root.")
    a("pause")
    a("")
    a(":end")


def main():
    core = read_list("fltk_core.list")
    gl = read_list("fltk_gl.list")

    lines = []
    emit(lines, core, gl)

    # Verify every emitted command fits the DOS command tail once %DC% expands.
    worst = 0
    for ln in lines:
        exp = ln.replace("%DC%", DC)
        if exp.startswith(("%s\\" % DC, DC)) or exp.startswith("C:\\"):
            worst = max(worst, len(exp))
            if len(exp) > LIMIT:
                sys.exit("command line %d > %d chars:\n  %s"
                         % (len(exp), LIMIT, exp))

    open(HDR, "w").write(HEADER)
    open(BAT, "wb").write("\r\n".join(lines).encode("ascii") + b"\r\n")

    print("wrote %s  (%d core + %d gl sources)" % (BAT, len(core), len(gl)))
    print("wrote %s" % HDR)
    print("longest command line: %d chars (DOS limit %d)" % (worst, LIMIT))


if __name__ == "__main__":
    main()
